var CLASS_NOTES_DATA = [
  {
    id: "c3",
    name: "Chapter 3",
    subtitle: "People, Family, Clothing, Items & Question Words",
    emoji: "👨‍👩‍👧‍👦",
    color: "#3B82F6",
    words: [
      { id: "cn_1", kanji: "人", hiragana: "ひと", romaji: "hito", meaning: "person", category: "c3", level: "N5", emoji: "👤", sentence: { ja: "あの人は誰ですか。", romaji: "Ano hito wa dare desu ka.", en: "Who is that person?" } },
      { id: "cn_2", kanji: "大人", hiragana: "おとな", romaji: "otona", meaning: "adult", category: "c3", level: "N5", emoji: "🧑", sentence: { ja: "大人は三人います。", romaji: "Otona wa sannin imasu.", en: "There are three adults." } },
      { id: "cn_3", kanji: "子供", hiragana: "こども", romaji: "kodomo", meaning: "child; children", category: "c3", level: "N5", emoji: "👧", sentence: { ja: "子供が遊んでいます。", romaji: "Kodomo ga asonde imasu.", en: "The children are playing." } },
      { id: "cn_4", kanji: "男", hiragana: "おとこ", romaji: "otoko", meaning: "male", category: "c3", level: "N5", emoji: "👨", sentence: { ja: "あの男の人は学生です。", romaji: "Ano otoko no hito wa gakusei desu.", en: "That man is a student." } },
      { id: "cn_5", kanji: "女", hiragana: "おんな", romaji: "onna", meaning: "female", category: "c3", level: "N5", emoji: "👩", sentence: { ja: "女の人が来ました。", romaji: "Onna no hito ga kimashita.", en: "A woman came." } },
      { id: "cn_6", kanji: "家族", hiragana: "かぞく", romaji: "kazoku", meaning: "family", category: "c3", level: "N5", emoji: "👨‍👩‍👧‍👦", sentence: { ja: "私の家族は四人です。", romaji: "Watashi no kazoku wa yonin desu.", en: "My family has four people." } },
      { id: "cn_7", kanji: "お父さん", hiragana: "おとうさん", romaji: "otousan", meaning: "father", category: "c3", level: "N5", emoji: "👨", sentence: { ja: "お父さんは会社員です。", romaji: "Otousan wa kaishain desu.", en: "My father is an office worker." } },
      { id: "cn_8", kanji: "お母さん", hiragana: "おかあさん", romaji: "okaasan", meaning: "mother", category: "c3", level: "N5", emoji: "👩", sentence: { ja: "お母さんは料理が上手です。", romaji: "Okaasan wa ryouri ga jouzu desu.", en: "My mother is good at cooking." } },
      { id: "cn_9", kanji: "息子", hiragana: "むすこ", romaji: "musuko", meaning: "son", category: "c3", level: "N5", emoji: "👦", sentence: { ja: "息子は学校に行きます。", romaji: "Musuko wa gakkou ni ikimasu.", en: "My son goes to school." } },
      { id: "cn_10", kanji: "娘", hiragana: "むすめ", romaji: "musume", meaning: "daughter", category: "c3", level: "N5", emoji: "👧", sentence: { ja: "娘は大学生です。", romaji: "Musume wa daigakusei desu.", en: "My daughter is a university student." } },
      { id: "cn_11", kanji: "友達", hiragana: "ともだち", romaji: "tomodachi", meaning: "friend", category: "c3", level: "N5", emoji: "🤝", sentence: { ja: "友達と映画を見ます。", romaji: "Tomodachi to eiga o mimasu.", en: "I watch a movie with my friend." } },
      { id: "cn_12", kanji: "帽子", hiragana: "ぼうし", romaji: "boushi", meaning: "hat; cap", category: "c3", level: "N5", emoji: "🧢", sentence: { ja: "帽子をかぶります。", romaji: "Boushi o kaburimasu.", en: "I wear a hat." } },
      { id: "cn_13", kanji: "眼鏡", hiragana: "めがね", romaji: "megane", meaning: "eyeglasses", category: "c3", level: "N5", emoji: "👓", sentence: { ja: "眼鏡をかけています。", romaji: "Megane o kakete imasu.", en: "I am wearing glasses." } },
      { id: "cn_14", kanji: "シャツ", hiragana: "シャツ", romaji: "shatsu", meaning: "shirt", category: "c3", level: "N5", emoji: "👔", sentence: { ja: "白いシャツを着ます。", romaji: "Shiroi shatsu o kimasu.", en: "I wear a white shirt." } },
      { id: "cn_15", kanji: "上着", hiragana: "うわぎ", romaji: "uwagi", meaning: "jacket", category: "c3", level: "N5", emoji: "🧥", sentence: { ja: "上着を脱いでください。", romaji: "Uwagi o nuide kudasai.", en: "Please take off your jacket." } },
      { id: "cn_16", kanji: "下着", hiragana: "したぎ", romaji: "shitagi", meaning: "underwear", category: "c3", level: "N5", emoji: "👕", sentence: { ja: "下着は毎日替えます。", romaji: "Shitagi wa mainichi kaemasu.", en: "I change underwear every day." } },
      { id: "cn_17", kanji: "スカート", hiragana: "スカート", romaji: "sukaato", meaning: "skirt", category: "c3", level: "N5", emoji: "👗", sentence: { ja: "赤いスカートを買いました。", romaji: "Akai sukaato o kaimashita.", en: "I bought a red skirt." } },
      { id: "cn_18", kanji: "ズボン", hiragana: "ズボン", romaji: "zubon", meaning: "pants", category: "c3", level: "N5", emoji: "👖", sentence: { ja: "新しいズボンが欲しいです。", romaji: "Atarashii zubon ga hoshii desu.", en: "I want new pants." } },
      { id: "cn_19", kanji: "靴下", hiragana: "くつした", romaji: "kutsushita", meaning: "socks", category: "c3", level: "N5", emoji: "🧦", sentence: { ja: "靴下を履きます。", romaji: "Kutsushita o hakimasu.", en: "I put on socks." } },
      { id: "cn_20", kanji: "靴", hiragana: "くつ", romaji: "kutsu", meaning: "shoes", category: "c3", level: "N5", emoji: "👟", sentence: { ja: "靴を脱いでください。", romaji: "Kutsu o nuide kudasai.", en: "Please take off your shoes." } },
      { id: "cn_21", kanji: "スニーカー", hiragana: "スニーカー", romaji: "suniikaa", meaning: "sneakers", category: "c3", level: "N5", emoji: "👟", sentence: { ja: "スニーカーで走ります。", romaji: "Suniikaa de hashirimasu.", en: "I run in sneakers." } },
      { id: "cn_22", kanji: "スリッパ", hiragana: "スリッパ", romaji: "surippa", meaning: "slippers", category: "c3", level: "N5", emoji: "🩴", sentence: { ja: "スリッパに履き替えてください。", romaji: "Surippa ni hakikaete kudasai.", en: "Please change into slippers." } },
      { id: "cn_23", kanji: "傘", hiragana: "かさ", romaji: "kasa", meaning: "umbrella", category: "c3", level: "N5", emoji: "☂️", sentence: { ja: "傘を持っていますか。", romaji: "Kasa o motte imasu ka.", en: "Do you have an umbrella?" } },
      { id: "cn_24", kanji: "本", hiragana: "ほん", romaji: "hon", meaning: "book", category: "c3", level: "N5", emoji: "📕", sentence: { ja: "この本は面白いです。", romaji: "Kono hon wa omoshiroi desu.", en: "This book is interesting." } },
      { id: "cn_25", kanji: "雑誌", hiragana: "ざっし", romaji: "zasshi", meaning: "magazine", category: "c3", level: "N5", emoji: "📰", sentence: { ja: "雑誌を読みます。", romaji: "Zasshi o yomimasu.", en: "I read a magazine." } },
      { id: "cn_26", kanji: "小説", hiragana: "しょうせつ", romaji: "shousetsu", meaning: "novel", category: "c3", level: "N5", emoji: "📖", sentence: { ja: "日本の小説を読んでいます。", romaji: "Nihon no shousetsu o yonde imasu.", en: "I am reading a Japanese novel." } },
      { id: "cn_27", kanji: "鍵", hiragana: "かぎ", romaji: "kagi", meaning: "key; lock", category: "c3", level: "N5", emoji: "🔑", sentence: { ja: "鍵をかけましたか。", romaji: "Kagi o kakemashita ka.", en: "Did you lock the door?" } },
      { id: "cn_28", kanji: "ビル", hiragana: "ビル", romaji: "biru", meaning: "building", category: "c3", level: "N5", emoji: "🏢", sentence: { ja: "あのビルは高いです。", romaji: "Ano biru wa takai desu.", en: "That building is tall." } },
      { id: "cn_29", kanji: "どれ", hiragana: "どれ", romaji: "dore", meaning: "which (one)", category: "c3", level: "N5", emoji: "❓", sentence: { ja: "どれが好きですか。", romaji: "Dore ga suki desu ka.", en: "Which one do you like?" } },
      { id: "cn_30", kanji: "どこ", hiragana: "どこ", romaji: "doko", meaning: "where", category: "c3", level: "N5", emoji: "📍", sentence: { ja: "トイレはどこですか。", romaji: "Toire wa doko desu ka.", en: "Where is the restroom?" } },
      { id: "cn_31", kanji: "どちら", hiragana: "どちら", romaji: "dochira", meaning: "which way", category: "c3", level: "N5", emoji: "↔️", sentence: { ja: "どちらが大きいですか。", romaji: "Dochira ga ookii desu ka.", en: "Which one is bigger?" } },
      { id: "cn_32", kanji: "何", hiragana: "なん", romaji: "nan", meaning: "what", category: "c3", level: "N5", emoji: "❔", sentence: { ja: "これは何ですか。", romaji: "Kore wa nan desu ka.", en: "What is this?" } },
      { id: "cn_33", kanji: "誰", hiragana: "だれ", romaji: "dare", meaning: "who", category: "c3", level: "N5", emoji: "🙋", sentence: { ja: "あの人は誰ですか。", romaji: "Ano hito wa dare desu ka.", en: "Who is that person?" } },
      { id: "cn_34", kanji: "誰の", hiragana: "だれの", romaji: "dare no", meaning: "whose", category: "c3", level: "N5", emoji: "🤔", sentence: { ja: "これは誰の本ですか。", romaji: "Kore wa dare no hon desu ka.", en: "Whose book is this?" } }
    ]
  },
  {
    id: "c4",
    name: "Chapter 4",
    subtitle: "Locatives, Places, Transportation & Rooms",
    emoji: "🏨",
    color: "#10B981",
    words: [
      { id: "cn_35", kanji: "前", hiragana: "まえ", romaji: "mae", meaning: "front", category: "c4", level: "N5", emoji: "⬆️", sentence: { ja: "駅の前にいます。", romaji: "Eki no mae ni imasu.", en: "I am in front of the station." } },
      { id: "cn_36", kanji: "後ろ", hiragana: "うしろ", romaji: "ushiro", meaning: "back; behind", category: "c4", level: "N5", emoji: "⬇️", sentence: { ja: "車の後ろにあります。", romaji: "Kuruma no ushiro ni arimasu.", en: "It is behind the car." } },
      { id: "cn_37", kanji: "中", hiragana: "なか", romaji: "naka", meaning: "inside", category: "c4", level: "N5", emoji: "📦", sentence: { ja: "箱の中に何がありますか。", romaji: "Hako no naka ni nani ga arimasu ka.", en: "What is inside the box?" } },
      { id: "cn_38", kanji: "外", hiragana: "そと", romaji: "soto", meaning: "outside", category: "c4", level: "N5", emoji: "🌳", sentence: { ja: "外は寒いです。", romaji: "Soto wa samui desu.", en: "It is cold outside." } },
      { id: "cn_39", kanji: "上", hiragana: "うえ", romaji: "ue", meaning: "top; above", category: "c4", level: "N5", emoji: "⬆️", sentence: { ja: "机の上に本があります。", romaji: "Tsukue no ue ni hon ga arimasu.", en: "There is a book on the desk." } },
      { id: "cn_40", kanji: "下", hiragana: "した", romaji: "shita", meaning: "under; below", category: "c4", level: "N5", emoji: "⬇️", sentence: { ja: "椅子の下に猫がいます。", romaji: "Isu no shita ni neko ga imasu.", en: "There is a cat under the chair." } },
      { id: "cn_41", kanji: "右", hiragana: "みぎ", romaji: "migi", meaning: "right", category: "c4", level: "N5", emoji: "➡️", sentence: { ja: "右に曲がってください。", romaji: "Migi ni magatte kudasai.", en: "Please turn right." } },
      { id: "cn_42", kanji: "左", hiragana: "ひだり", romaji: "hidari", meaning: "left", category: "c4", level: "N5", emoji: "⬅️", sentence: { ja: "左に銀行があります。", romaji: "Hidari ni ginkou ga arimasu.", en: "There is a bank on the left." } },
      { id: "cn_43", kanji: "近く", hiragana: "ちかく", romaji: "chikaku", meaning: "near", category: "c4", level: "N5", emoji: "📏", sentence: { ja: "駅の近くに住んでいます。", romaji: "Eki no chikaku ni sunde imasu.", en: "I live near the station." } },
      { id: "cn_44", kanji: "隣", hiragana: "となり", romaji: "tonari", meaning: "beside; next to", category: "c4", level: "N5", emoji: "↔️", sentence: { ja: "隣の部屋は静かです。", romaji: "Tonari no heya wa shizuka desu.", en: "The room next door is quiet." } },
      { id: "cn_45", kanji: "向こう", hiragana: "むこう", romaji: "mukou", meaning: "across", category: "c4", level: "N5", emoji: "🔄", sentence: { ja: "向こうにコンビニがあります。", romaji: "Mukou ni konbini ga arimasu.", en: "There is a convenience store across the way." } },
      { id: "cn_46", kanji: "間", hiragana: "あいだ", romaji: "aida", meaning: "in between", category: "c4", level: "N5", emoji: "↔️", sentence: { ja: "銀行と郵便局の間にあります。", romaji: "Ginkou to yuubinkyoku no aida ni arimasu.", en: "It is between the bank and the post office." } },
      { id: "cn_47", kanji: "予約", hiragana: "よやく", romaji: "yoyaku", meaning: "reservation", category: "c4", level: "N5", emoji: "📋", sentence: { ja: "ホテルの予約をしました。", romaji: "Hoteru no yoyaku o shimashita.", en: "I made a hotel reservation." } },
      { id: "cn_48", kanji: "旅館", hiragana: "りょかん", romaji: "ryokan", meaning: "Japanese traditional inn", category: "c4", level: "N5", emoji: "🏯", sentence: { ja: "旅館に泊まります。", romaji: "Ryokan ni tomarimasu.", en: "I will stay at a traditional inn." } },
      { id: "cn_49", kanji: "温泉", hiragana: "おんせん", romaji: "onsen", meaning: "hot spring", category: "c4", level: "N5", emoji: "♨️", sentence: { ja: "温泉に入りたいです。", romaji: "Onsen ni hairitai desu.", en: "I want to go to a hot spring." } },
      { id: "cn_50", kanji: "駐車場", hiragana: "ちゅうしゃじょう", romaji: "chuushajou", meaning: "parking lot", category: "c4", level: "N5", emoji: "🅿️", sentence: { ja: "駐車場はどこですか。", romaji: "Chuushajou wa doko desu ka.", en: "Where is the parking lot?" } },
      { id: "cn_51", kanji: "玄関", hiragana: "げんかん", romaji: "genkan", meaning: "entrance way", category: "c4", level: "N5", emoji: "🚪", sentence: { ja: "玄関で靴を脱ぎます。", romaji: "Genkan de kutsu o nugimasu.", en: "I take off my shoes at the entrance." } },
      { id: "cn_52", kanji: "ロビー", hiragana: "ロビー", romaji: "robii", meaning: "lobby", category: "c4", level: "N5", emoji: "🏛️", sentence: { ja: "ロビーで待っています。", romaji: "Robii de matte imasu.", en: "I am waiting in the lobby." } },
      { id: "cn_53", kanji: "お風呂", hiragana: "おふろ", romaji: "ofuro", meaning: "bath; bathtub", category: "c4", level: "N5", emoji: "🛁", sentence: { ja: "お風呂に入ります。", romaji: "Ofuro ni hairimasu.", en: "I take a bath." } },
      { id: "cn_54", kanji: "食堂", hiragana: "しょくどう", romaji: "shokudou", meaning: "dining hall; cafeteria", category: "c4", level: "N5", emoji: "🍽️", sentence: { ja: "食堂でご飯を食べます。", romaji: "Shokudou de gohan o tabemasu.", en: "I eat at the cafeteria." } },
      { id: "cn_55", kanji: "電車", hiragana: "でんしゃ", romaji: "densha", meaning: "train", category: "c4", level: "N5", emoji: "🚃", sentence: { ja: "電車で会社に行きます。", romaji: "Densha de kaisha ni ikimasu.", en: "I go to work by train." } },
      { id: "cn_56", kanji: "バス", hiragana: "バス", romaji: "basu", meaning: "bus", category: "c4", level: "N5", emoji: "🚌", sentence: { ja: "バスに乗ります。", romaji: "Basu ni norimasu.", en: "I ride the bus." } },
      { id: "cn_57", kanji: "車", hiragana: "くるま", romaji: "kuruma", meaning: "car", category: "c4", level: "N5", emoji: "🚗", sentence: { ja: "車で来ました。", romaji: "Kuruma de kimashita.", en: "I came by car." } },
      { id: "cn_58", kanji: "アパート", hiragana: "アパート", romaji: "apaato", meaning: "apartment", category: "c4", level: "N5", emoji: "🏢", sentence: { ja: "アパートに住んでいます。", romaji: "Apaato ni sunde imasu.", en: "I live in an apartment." } },
      { id: "cn_59", kanji: "ビル", hiragana: "ビル", romaji: "biru", meaning: "building", category: "c4", level: "N5", emoji: "🏢", sentence: { ja: "このビルは新しいです。", romaji: "Kono biru wa atarashii desu.", en: "This building is new." } },
      { id: "cn_60", kanji: "オフィス", hiragana: "オフィス", romaji: "ofisu", meaning: "office", category: "c4", level: "N5", emoji: "🏛️", sentence: { ja: "オフィスは五階にあります。", romaji: "Ofisu wa gokai ni arimasu.", en: "The office is on the fifth floor." } },
      { id: "cn_61", kanji: "会議室", hiragana: "かいぎしつ", romaji: "kaigishitsu", meaning: "meeting room", category: "c4", level: "N5", emoji: "📊", sentence: { ja: "会議室を予約しました。", romaji: "Kaigishitsu o yoyaku shimashita.", en: "I reserved the meeting room." } },
      { id: "cn_62", kanji: "エレベーター", hiragana: "エレベーター", romaji: "erebeetaa", meaning: "elevator", category: "c4", level: "N5", emoji: "🛗", sentence: { ja: "エレベーターで上がります。", romaji: "Erebeetaa de agarimasu.", en: "I go up by elevator." } },
      { id: "cn_63", kanji: "エスカレーター", hiragana: "エスカレーター", romaji: "esukareetaa", meaning: "escalator", category: "c4", level: "N5", emoji: "📐", sentence: { ja: "エスカレーターで下ります。", romaji: "Esukareetaa de orimasu.", en: "I go down by escalator." } },
      { id: "cn_64", kanji: "階段", hiragana: "かいだん", romaji: "kaidan", meaning: "stairs", category: "c4", level: "N5", emoji: "🪜", sentence: { ja: "階段を上がります。", romaji: "Kaidan o agarimasu.", en: "I go up the stairs." } },
      { id: "cn_65", kanji: "部屋", hiragana: "へや", romaji: "heya", meaning: "room", category: "c4", level: "N5", emoji: "🚪", sentence: { ja: "部屋は広いです。", romaji: "Heya wa hiroi desu.", en: "The room is spacious." } },
      { id: "cn_66", kanji: "庭", hiragana: "にわ", romaji: "niwa", meaning: "garden", category: "c4", level: "N5", emoji: "🌿", sentence: { ja: "庭に花があります。", romaji: "Niwa ni hana ga arimasu.", en: "There are flowers in the garden." } },
      { id: "cn_67", kanji: "お店", hiragana: "おみせ", romaji: "omise", meaning: "store", category: "c4", level: "N5", emoji: "🏪", sentence: { ja: "あのお店は安いです。", romaji: "Ano omise wa yasui desu.", en: "That store is cheap." } },
      { id: "cn_68", kanji: "お土産", hiragana: "おみやげ", romaji: "omiyage", meaning: "souvenir", category: "c4", level: "N5", emoji: "🎁", sentence: { ja: "お土産を買いました。", romaji: "Omiyage o kaimashita.", en: "I bought a souvenir." } },
      { id: "cn_69", kanji: "机", hiragana: "つくえ", romaji: "tsukue", meaning: "desk", category: "c4", level: "N5", emoji: "🪑", sentence: { ja: "机の上にパソコンがあります。", romaji: "Tsukue no ue ni pasokon ga arimasu.", en: "There is a computer on the desk." } },
      { id: "cn_70", kanji: "テーブル", hiragana: "テーブル", romaji: "teeburu", meaning: "table", category: "c4", level: "N5", emoji: "🍽️", sentence: { ja: "テーブルを拭きます。", romaji: "Teeburu o fukimasu.", en: "I wipe the table." } },
      { id: "cn_71", kanji: "椅子", hiragana: "いす", romaji: "isu", meaning: "chair", category: "c4", level: "N5", emoji: "🪑", sentence: { ja: "椅子に座ってください。", romaji: "Isu ni suwatte kudasai.", en: "Please sit on the chair." } },
      { id: "cn_72", kanji: "仕事", hiragana: "しごと", romaji: "shigoto", meaning: "work", category: "c4", level: "N5", emoji: "💼", sentence: { ja: "仕事は何ですか。", romaji: "Shigoto wa nan desu ka.", en: "What is your job?" } },
      { id: "cn_73", kanji: "お金", hiragana: "おかね", romaji: "okane", meaning: "money", category: "c4", level: "N5", emoji: "💰", sentence: { ja: "お金が足りません。", romaji: "Okane ga tarimasen.", en: "I don't have enough money." } }
    ]
  },
  {
    id: "c5",
    name: "Chapter 5",
    subtitle: "People, Utensils, Titles, Animals, Condiments & Rooms",
    emoji: "🍳",
    color: "#8B5CF6",
    words: [
      { id: "cn_74", kanji: "クラスメイト", hiragana: "クラスメイト", romaji: "kurasumeito", meaning: "classmate", category: "c5", level: "N5", emoji: "🎓", sentence: { ja: "クラスメイトと話します。", romaji: "Kurasumeito to hanashimasu.", en: "I talk with my classmate." } },
      { id: "cn_75", kanji: "同僚", hiragana: "どうりょう", romaji: "douryou", meaning: "colleague", category: "c5", level: "N4", emoji: "👔", sentence: { ja: "同僚と昼ご飯を食べます。", romaji: "Douryou to hirugohan o tabemasu.", en: "I eat lunch with my colleague." } },
      { id: "cn_76", kanji: "警察", hiragana: "けいさつ", romaji: "keisatsu", meaning: "police officer", category: "c5", level: "N5", emoji: "👮", sentence: { ja: "警察に聞いてください。", romaji: "Keisatsu ni kiite kudasai.", en: "Please ask the police." } },
      { id: "cn_77", kanji: "駅員", hiragana: "えきいん", romaji: "ekiin", meaning: "station worker", category: "c5", level: "N5", emoji: "🚉", sentence: { ja: "駅員に聞きましょう。", romaji: "Ekiin ni kikimashou.", en: "Let's ask the station worker." } },
      { id: "cn_78", kanji: "サングラス", hiragana: "サングラス", romaji: "sangurasu", meaning: "sunglasses", category: "c5", level: "N5", emoji: "🕶️", sentence: { ja: "サングラスをかけます。", romaji: "Sangurasu o kakemasu.", en: "I put on sunglasses." } },
      { id: "cn_79", kanji: "紙", hiragana: "かみ", romaji: "kami", meaning: "paper", category: "c5", level: "N5", emoji: "📄", sentence: { ja: "紙に書いてください。", romaji: "Kami ni kaite kudasai.", en: "Please write on the paper." } },
      { id: "cn_80", kanji: "スプーン", hiragana: "スプーン", romaji: "supuun", meaning: "spoon", category: "c5", level: "N5", emoji: "🥄", sentence: { ja: "スプーンでスープを飲みます。", romaji: "Supuun de suupu o nomimasu.", en: "I eat soup with a spoon." } },
      { id: "cn_81", kanji: "フォーク", hiragana: "フォーク", romaji: "fooku", meaning: "fork", category: "c5", level: "N5", emoji: "🍴", sentence: { ja: "フォークでサラダを食べます。", romaji: "Fooku de sarada o tabemasu.", en: "I eat salad with a fork." } },
      { id: "cn_82", kanji: "箸", hiragana: "はし", romaji: "hashi", meaning: "chopsticks", category: "c5", level: "N5", emoji: "🥢", sentence: { ja: "箸を使えますか。", romaji: "Hashi o tsukaemasu ka.", en: "Can you use chopsticks?" } },
      { id: "cn_83", kanji: "ナイフ", hiragana: "ナイフ", romaji: "naifu", meaning: "knife", category: "c5", level: "N5", emoji: "🔪", sentence: { ja: "ナイフで切ります。", romaji: "Naifu de kirimasu.", en: "I cut with a knife." } },
      { id: "cn_84", kanji: "社長", hiragana: "しゃちょう", romaji: "shachou", meaning: "company president", category: "c5", level: "N4", emoji: "👨‍💼", sentence: { ja: "社長は今会議中です。", romaji: "Shachou wa ima kaigichuu desu.", en: "The president is in a meeting now." } },
      { id: "cn_85", kanji: "部長", hiragana: "ぶちょう", romaji: "buchou", meaning: "department head", category: "c5", level: "N4", emoji: "👔", sentence: { ja: "部長に報告します。", romaji: "Buchou ni houkoku shimasu.", en: "I will report to the department head." } },
      { id: "cn_86", kanji: "課長", hiragana: "かちょう", romaji: "kachou", meaning: "supervisor", category: "c5", level: "N4", emoji: "📋", sentence: { ja: "課長に相談します。", romaji: "Kachou ni soudan shimasu.", en: "I will consult with the supervisor." } },
      { id: "cn_87", kanji: "犬", hiragana: "いぬ", romaji: "inu", meaning: "dog", category: "c5", level: "N5", emoji: "🐕", sentence: { ja: "犬が好きです。", romaji: "Inu ga suki desu.", en: "I like dogs." } },
      { id: "cn_88", kanji: "猫", hiragana: "ねこ", romaji: "neko", meaning: "cat", category: "c5", level: "N5", emoji: "🐈", sentence: { ja: "猫がいます。", romaji: "Neko ga imasu.", en: "There is a cat." } },
      { id: "cn_89", kanji: "鳥", hiragana: "とり", romaji: "tori", meaning: "bird", category: "c5", level: "N5", emoji: "🐦", sentence: { ja: "鳥が飛んでいます。", romaji: "Tori ga tonde imasu.", en: "A bird is flying." } },
      { id: "cn_90", kanji: "虫", hiragana: "むし", romaji: "mushi", meaning: "insect", category: "c5", level: "N5", emoji: "🐛", sentence: { ja: "虫が怖いです。", romaji: "Mushi ga kowai desu.", en: "I am afraid of insects." } },
      { id: "cn_91", kanji: "毛布", hiragana: "もうふ", romaji: "moufu", meaning: "blanket", category: "c5", level: "N5", emoji: "🛏️", sentence: { ja: "毛布は暖かいです。", romaji: "Moufu wa atatakai desu.", en: "The blanket is warm." } },
      { id: "cn_92", kanji: "枕", hiragana: "まくら", romaji: "makura", meaning: "pillow", category: "c5", level: "N5", emoji: "🛌", sentence: { ja: "この枕は柔らかいです。", romaji: "Kono makura wa yawarakai desu.", en: "This pillow is soft." } },
      { id: "cn_93", kanji: "胡椒", hiragana: "こしょう", romaji: "koshou", meaning: "pepper", category: "c5", level: "N5", emoji: "🌶️", sentence: { ja: "胡椒をかけますか。", romaji: "Koshou o kakemasu ka.", en: "Would you like pepper?" } },
      { id: "cn_94", kanji: "醤油", hiragana: "しょうゆ", romaji: "shouyu", meaning: "soy sauce", category: "c5", level: "N5", emoji: "🫗", sentence: { ja: "醤油を取ってください。", romaji: "Shouyu o totte kudasai.", en: "Please pass the soy sauce." } },
      { id: "cn_95", kanji: "塩", hiragana: "しお", romaji: "shio", meaning: "salt", category: "c5", level: "N5", emoji: "🧂", sentence: { ja: "塩を少し入れます。", romaji: "Shio o sukoshi iremasu.", en: "I add a little salt." } },
      { id: "cn_96", kanji: "砂糖", hiragana: "さとう", romaji: "satou", meaning: "sugar", category: "c5", level: "N5", emoji: "🍬", sentence: { ja: "コーヒーに砂糖を入れますか。", romaji: "Koohii ni satou o iremasu ka.", en: "Do you put sugar in your coffee?" } },
      { id: "cn_97", kanji: "台所", hiragana: "だいどころ", romaji: "daidokoro", meaning: "kitchen", category: "c5", level: "N5", emoji: "🍳", sentence: { ja: "台所で料理を作ります。", romaji: "Daidokoro de ryouri o tsukurimasu.", en: "I cook in the kitchen." } },
      { id: "cn_98", kanji: "居間", hiragana: "いま", romaji: "ima", meaning: "living room", category: "c5", level: "N5", emoji: "🛋️", sentence: { ja: "居間でテレビを見ます。", romaji: "Ima de terebi o mimasu.", en: "I watch TV in the living room." } },
      { id: "cn_99", kanji: "ベランダ", hiragana: "ベランダ", romaji: "beranda", meaning: "veranda", category: "c5", level: "N5", emoji: "🌅", sentence: { ja: "ベランダから山が見えます。", romaji: "Beranda kara yama ga miemasu.", en: "You can see mountains from the veranda." } },
      { id: "cn_100", kanji: "木", hiragana: "き", romaji: "ki", meaning: "tree", category: "c5", level: "N5", emoji: "🌳", sentence: { ja: "庭に大きい木があります。", romaji: "Niwa ni ookii ki ga arimasu.", en: "There is a big tree in the garden." } }
    ]
  }
];
